### ISSUE TITLE
@Fatfritz2

### ISSUE THREAD

**Issue by Justaposture** [Justaposture/-i019211#1]

**Comment by FatFritz2** [comment]
oh hi

**Comment by FatFritz2** [comment]
i am here

**Comment by Justaposture** [comment]
all right . First step:
go to codespace and then in there go to extention part.Then in the search bar type docker.

**Comment by FatFritz2** [comment]
ok

**Comment by Justaposture** [comment]
click it and install it.

**Comment by FatFritz2** [comment]
where is the extension part

**Comment by FatFritz2** [comment]
![image](https://user-images.githubusercontent.com/107122824/231808845-ca063cf8-67ed-4f58-a3f1-6585f6cfe75d.png)

**Comment by Justaposture** [comment]
go to your botli fork. Then try it

**Comment by FatFritz2** [comment]
![image](https://user-images.githubusercontent.com/107122824/231809422-775462cb-b073-4373-baa2-df4c88702a94.png)

**Comment by Justaposture** [comment]
go ahead and install the docker

**Comment by Justaposture** [comment]
first one

**Comment by FatFritz2** [comment]
will try bro :D

**Comment by Justaposture** [comment]
remember this. when you use this, this will not be 24/7 program. you have to turn it off and turn it on again and again.

**Comment by FatFritz2** [comment]
done 
![image](https://user-images.githubusercontent.com/107122824/231810249-8fe986b8-62ce-4657-aa57-576361c53e3f.png)

**Comment by Justaposture** [comment]
> remember this. when you use this, this will not be 24/7 program. you have to turn it off and turn it on again and again.

and nps :- about 1M
Nodes:- about  1M

**Comment by FatFritz2** [comment]
> ot be 24

ok

**Comment by FatFritz2** [comment]
thats quite decent now what

**Comment by Justaposture** [comment]
> done ![image](https://user-images.githubusercontent.com/107122824/231810249-8fe986b8-62ce-4657-aa57-576361c53e3f.png)

next step

in the terminal type "docker build -t local:latest ." - here "." this is also important
then to run the code type "docker run -it local:latest"

**Comment by Justaposture** [comment]
send me an img after you tried those two commands

**Comment by FatFritz2** [comment]
ok wait

**Comment by Justaposture** [comment]
did you try them??

**Comment by FatFritz2** [comment]
its being built

**Comment by Justaposture** [comment]
great news

**Comment by FatFritz2** [comment]
![image](https://user-images.githubusercontent.com/107122824/231811740-a36ad681-21a0-4c42-82f9-c651ea5cbb53.png)

**Comment by FatFritz2** [comment]
pls wait a bit gonna take 5 minutes :3

**Comment by FatFritz2** [comment]
Oh no i have to add the token : ```
Traceback (most recent call last):
  File "//user_interface.py", line 276, in <module>
    ui = UserInterface(args.config, args.non_interactive, args.matchmaking, args.upgrade)
  File "//user_interface.py", line 41, in __init__
    self.api = API(self.config['token'])
  File "/api.py", line 20, in __init__
    self.session.headers.update({'User-Agent': f'BotLi user:{self.user["username"]}'})
KeyError: 'username'
```

**Comment by Justaposture** [comment]
here I have to tell you something. when you run this for about 10 minutes They will give you a warning to stop the app. My recommendation is monitor the console and when the error comes , then stop the program. use it after 5minutes

**Comment by FatFritz2** [comment]
Ok still fixing the problem

**Comment by FatFritz2** [comment]
ok its done now what

**Comment by Justaposture** [comment]
> > done ![image](https://user-images.githubusercontent.com/107122824/231810249-8fe986b8-62ce-4657-aa57-576361c53e3f.png)
> 
> next step
> 
> in the terminal type "docker build -t local:latest ." - here "." this is also important then to run the code type "docker run -it local:latest"

**Comment by Justaposture** [comment]
find that msg

**Comment by Justaposture** [comment]
in there I told you everything

**Comment by FatFritz2** [comment]
WHY ???
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile

**Comment by FatFritz2** [comment]
oh still rebuilding :((

**Comment by Justaposture** [comment]
done??

**Comment by FatFritz2** [comment]
no still step 3/7

**Comment by FatFritz2** [comment]
![image](https://user-images.githubusercontent.com/107122824/231814972-e019bd06-82ef-461a-b348-73d6f0bf6b60.png)
srry

**Comment by FatFritz2** [comment]
ok now doing the 2nd command

**Comment by FatFritz2** [comment]
YESS IT WORKS :
![image](https://user-images.githubusercontent.com/107122824/231815283-88bfa9e4-68ad-4447-98cd-622085cfa058.png)

**Comment by Justaposture** [comment]
nice

**Comment by FatFritz2** [comment]
and now after this how to preserve the bot

**Comment by Justaposture** [comment]
there is no preservation. you have to use it like a normal cmd program. Have to turn it on and off

**Comment by FatFritz2** [comment]
how to turn on ?

**Comment by Justaposture** [comment]
> how to turn on ?

Just type the last command I sent.
Docker run .........................

**Comment by FatFritz2** [comment]
ok thanks master :D

**Comment by Justaposture** [comment]
the same thing I do with myec2

**Comment by Justaposture** [comment]
> the same thing I do with myec2

to reduce the cost I do it

**Comment by FatFritz2** [comment]
hey I also have a 2nd bot on lichess

**Comment by Justaposture** [comment]
> hey I also have a 2nd bot on lichess

name??

**Comment by FatFritz2** [comment]
Its TorBot. Btw is using codespaces cost me >_<

**Comment by Justaposture** [comment]
> Its TorBot. Btw is using codespaces cost me >_<

really??. That's what I said

**Comment by Justaposture** [comment]
> > Its TorBot. Btw is using codespaces cost me >_<
> 
> really??. That's what I said

more trouble

**Comment by FatFritz2** [comment]
ig its free or sth

**Comment by Justaposture** [comment]
> ig its free or sth

it's free

**Comment by FatFritz2** [comment]
OH YEA THANKS NOW I can go now bye ig

**Comment by Justaposture** [comment]
bye

**Comment by FatFritz2** [comment]
btw do u have email

**Comment by Justaposture** [comment]
> btw do u have email

ya  botmikail@outlook.com

**Comment by FatFritz2** [comment]
ok pls show me yours

**Comment by FatFritz2** [comment]
bc its easier to contact via gmail tho

**Comment by Justaposture** [comment]
ok
